/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author user
 */
public class AppPenampilGambarFullGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppPenampilGambarFullGUI
     */
    public AppPenampilGambarFullGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonpanel = new javax.swing.JPanel();
        spongebob = new javax.swing.JButton();
        patrick = new javax.swing.JButton();
        squidward = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        squidwardlb = new javax.swing.JLabel();
        spongeboblb = new javax.swing.JLabel();
        patricklb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        spongebob.setText("spongebob");
        spongebob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spongebobActionPerformed(evt);
            }
        });
        buttonpanel.add(spongebob);

        patrick.setText("patrick");
        patrick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patrickActionPerformed(evt);
            }
        });
        buttonpanel.add(patrick);

        squidward.setText("squidward");
        squidward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squidwardActionPerformed(evt);
            }
        });
        buttonpanel.add(squidward);

        exitbutton.setText("exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        buttonpanel.add(exitbutton);

        getContentPane().add(buttonpanel, java.awt.BorderLayout.CENTER);

        imagepanel.setLayout(new java.awt.CardLayout());

        squidwardlb.setIcon(new javax.swing.ImageIcon("D:\\squidword.jpg")); // NOI18N
        imagepanel.add(squidwardlb, "2");

        spongeboblb.setIcon(new javax.swing.ImageIcon("D:\\Spongebob-squarepants.png")); // NOI18N
        spongeboblb.setMaximumSize(new java.awt.Dimension(135, 35));
        imagepanel.add(spongeboblb, "0");

        patricklb.setIcon(new javax.swing.ImageIcon("D:\\patrick.jpg")); // NOI18N
        imagepanel.add(patricklb, "1");

        getContentPane().add(imagepanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spongebobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spongebobActionPerformed
        CardLayout cl = (CardLayout) (imagepanel.getLayout()) ;
        cl.show(imagepanel, "0");
    }//GEN-LAST:event_spongebobActionPerformed

    private void patrickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrickActionPerformed
        CardLayout cl = (CardLayout) (imagepanel.getLayout()) ;
        cl.show(imagepanel, "1");
    }//GEN-LAST:event_patrickActionPerformed

    private void squidwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squidwardActionPerformed
        CardLayout cl = (CardLayout) (imagepanel.getLayout()) ;
        cl.show(imagepanel, "2");
    }//GEN-LAST:event_squidwardActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambarFullGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambarFullGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambarFullGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambarFullGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               AppPenampilGambarFullGUI fullFrame = new AppPenampilGambarFullGUI();
               
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JButton exitbutton;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JButton patrick;
    private javax.swing.JLabel patricklb;
    private javax.swing.JButton spongebob;
    private javax.swing.JLabel spongeboblb;
    private javax.swing.JButton squidward;
    private javax.swing.JLabel squidwardlb;
    // End of variables declaration//GEN-END:variables
}
